version: '3.8'

services:
  api:
    build: .
    container_name: solidqms-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:secretpassword@db:5432/solidqms_ai

  db:
    image: postgres:15
    container_name: solidqms-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: solidqms_ai
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: